sudo: required
services:
    - docker

before_install:
    - docker build -t kalpit/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kalpit/docker-react npm run test 

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucker_name: "elasticbeanstalk-us-east-2-209399450717"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id:
        secure: $AWS_ACCESS_KEY    
    secret_access_key:
        secure: $AWS_SECRET_KEY
