sudo: required
services:
    - docker

before_install:
    - docker build -t kalpit/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true kalpit/docker-react npm run test -- --coverage
